### PR TITLE
add options to send the values to separate mqtt topics and disable json payload

### PR DESCRIPTION
**Pull request by zivillian**
There are two new options:
- `-s` to enable also sending all values to separate mqtt topics
- `--disable-json` to disable the json message (if not needed)

 successor of #13

### CODE REVIEW

**Comment by copystring** [comment]
I had a quick look. Looks good if you ask me 👍

**Comment by copystring** [comment]
So I had a little play with this and found some boolean values in separate values have an capital first letter and those in the json don't. Those with capital letter are recognized as string instead of boolean by iobroker (and maybe some other systems I assume)

Please make it "true" boolean by making the boolean values lower case.

image

**Comment by zivillian** [comment]
can you test the build from https://github.com/zivillian/ism7mqtt/actions/runs/1888876529

**Comment by copystring** [comment]
Yes. The values I have are now correct.

**Pull request merged**
