### PR TITLE
Home Assistant discovery

### PR DESCRIPTION
**Pull request by b3nn0**
Hi,
I started to work on auto-discovery for Home Assistant. It already works somewhat, but is far from finished. Wanted to open the PR already so you know I'm working on it and can intervene if you don't like how it's implemented.

Note that I'm not really a C# guy. Only did some stuff in it many years ago, but it was much more basic back then, so this is probably written in a bit of an old-fashioned way.

EDIT: One thing that's a bit annoying..:
There are some attributes that use a BinaryReadOnlyConverterTemplate because they only know two states.
Ism7Mqtt will publish them as true/false, however, that doesn't make much sense for stuff like this:
```
    <ListParameterDescriptor PTID="10021">
      <Name>3-Wege-Umschaltventil</Name>
      <Protocol>true</Protocol>
      <App>true</App>
      <RemoveConditionId>C_950</RemoveConditionId>
      <ReadOnlyConditionId>True</ReadOnlyConditionId>
      <InactiveConditionId>False</InactiveConditionId>
      <IsSnapshotTransmitEnabled>false</IsSnapshotTransmitEnabled>
      <ControlType>ComboBoxText</ControlType>
      <KeyValueList>0;Heizung;1;Warmwasser</KeyValueList>
    </ListParameterDescriptor>
```
Wolf describes it as a Combo Box with two distinct values, for which true/false doesn't make much sense

Would you mind if I try to change that, so if the KeyValueList is something that doesn't look like "0;Aus;1;An" or "0;Deaktiviert;1;Aktiviert" would in fact not use the boolean converter, but just remain as a normal list parameter?
It would be an incompatible change though.

### CODE REVIEW

**Comment by b3nn0** [comment]
Some impressions when running it with `--hass-id=heizung`:
grafik
grafik
grafik
grafik


Still some oddities in there though..

**Comment by b3nn0** [comment]
Alright.. I'm fairly happy with how it works now. Mind taking a look and/or creating a beta build so more people can test it? I'm almost certain that some things could be improved wrt. HA integration.

Incompatibilities:
- It is not 100% backwards compatible, because as written in the original post, stuff like "3-Wege-Ventil" will now report as "Heizung"/"Warmwasser" instead of false/true. This should be the case for all list-type-parameters that contain two entries in the list, which are either Ein/Aus or Aktiviert/Deaktiviert

Not so nice things:
What I don't really like, but it is like that upstream, is the fact that when JSON-Keys get published as separate topics, they will be laundered, e.g. replacing a blank with an underscore: https://github.com/zivillian/ism7mqtt/blob/d6ef3c48d781d83686d3037787974a80958bb16d/src/ism7mqtt/Program.cs#L258
However, when using /set/, this laundering is not allowed, but instead, the parameters SafeName has to be used: https://github.com/zivillian/ism7mqtt/blob/d6ef3c48d781d83686d3037787974a80958bb16d/src/ism7mqtt/ISM7/Xml/ParameterDescriptor.cs#L33

This makes the bavior quite unintuitive when people use the seperate-topic-interface, because one has to read from e.g. `/...../1x_Warmwasser`, but has to write to `/..../1x Warmwasser`. This PR handles this correctly, but my suggestion would be to also replace / and blank in the SafeName and use that for everything. That would also change it in the JSON though, so another incompatible change.

What I don't know about:
There is this one parameter "Programmwahl"/"Programmwahl Gemeinsam" which is double-nested and contains not only value/text, but also a number around it (as can be seen in your own README.md).
This PR does not handle it correctly. It will be reported to HA with a value of "35012", which is not a valid choice. HA will log a warning about it and then ignore it. So it's not dramatic, but I have no idea how I would have to handle it correctly.

**Comment by infocfc** [comment]
This looks absolutely *AWESOME*. I can't wait to test it, I hope I have time between "the days".

**Comment by zivillian** [comment]
First of all - a big thanks! I'm impressed, and it would have taken me weeks to get to this point! I'll take a look at the code - should I just push my edits or do you prefer comments in the code review?

> Mind[...] creating a beta build so more people can test it? 

I've enabled the github action and also created a docker image - so everyone can test by using either the build output from the [Artifacts on the Checks tab](https://github.com/zivillian/ism7mqtt/pull/35/checks) or the [zivillian/ism7mqtt:ha-discovery](https://hub.docker.com/r/zivillian/ism7mqtt/tags) docker image. The artifacts will automatically update with each change to this pr - the docker image needs to be updated by me.

> It is not 100% backwards compatible

I'm totally fine with this - it's still an early unstable beta, so thing may change or break.

> Not so nice things

I thought I've fixed this in #32 - definitly a thing I will look into again.

> There is this one parameter "Programmwahl"/"Programmwahl Gemeinsam" 

For now I'd say, we ignore this, because I don't think it's a use case to have duplicate parameters. This may happen during the initial setup, but can easily be fixed by just removing one of the duplicate parameters.

**Comment by b3nn0** [comment]
> should I just push my edits or do you prefer comments in the code review?

Whatever you prefer. Feel free to edit directly.

One more thing I forgot to mention: I think the original code expected - when using a German locale - that decimal values ("Warmwasserminimaltemperatur" = 55.5) would have to be set with a , instead of a . - i.e. 55,5.
I hardcoded the locale for the Double.TryParse call.. not sure if it's done in a proper way though, but it fixed it for me.



> I thought I've fixed this in https://github.com/zivillian/ism7mqtt/pull/32 - definitly a thing I will look into again.

Unfortunately not. It still matches against the SafeName here:
https://github.com/zivillian/ism7mqtt/blob/d6ef3c48d781d83686d3037787974a80958bb16d/src/ism7mqtt/ISM7/Ism7Config.cs#L193
but in that one, _ and / are not replaced. Only umlauts.

**Comment by b3nn0** [comment]
Thanks for the refactor - looks much more modern-C#-y now!

I now also created a Home Assistant Add-on repository, which makes it really simple to configure and run ism7mqtt inside HA. The only not-so-easy part is creating the parameters.json
See: https://github.com/b3nn0/hassio-addon-ism7mqtt

This Repository can be added in the Home Assistant UI and can then be installed and configured:
grafik
grafik


I will now switch my setup over to this and see how it goes..

**Comment by b3nn0** [comment]
Alright, fixed a couple of bugs for HA and added support for duplicate-name parameters.
Also now passing OtherParameterDescriptors to HA.
The IsWritable flag is respected for this, so controls that have IsWritable set as true, will result in an editable text field in HA.
Editing will fail though, e.g. with this error: CTID '33004' is not yet implemented
Is writing actually implemented for any of the OtherParameterDescriptors? Or is this generally not supported yet?
If it isn't it would probably make sense to just discover them through as sensors, and ignore the IsWritable value.

I also noticed, that some of these sensors look a bit strange - some of them are published with a quoted string, and some of them with an unquoted string:
grafik

Is this an oddity coming from the Parameters.xml itself? Or is it caused by ism7mqtt?

Anyway, mind triggering a new docker build, so I can update the add-on? Right now it directly references your docker builds on this PR.

**Comment by zivillian** [comment]
@b3nn0 regarding the OtherParameterDescriptors - I'm fine with this - if there is a useful output for any parameter, it can be seen in HA - if there are only values like yours, those can easily be removed from the parameters.json. I removed almost all parameters from my BM device, since they were useless for me.

**Comment by zivillian** [comment]
> Is writing actually implemented for any of the OtherParameterDescriptors

I'm not sure, but most of the converters are readonly, because I don't have any test data or use case. This may change, if someone want's to send a schedule via mqtt.

**Comment by b3nn0** [comment]
> I refactored a bit more, to move the HA discovery to a separate class and also triggered a new docker build.

Nice, I guess the function grew a bit larger than I originally thought it would.. so makes sense.

> regarding the OtherParameterDescriptors - I'm fine with this - if there is a useful output for any parameter, it can be seen in HA - if there are only values like yours, those can easily be removed from the parameters.json. I removed almost all parameters from my BM device, since they were useless for me.

Makes sense. I guess some user-common-sense is required to strip down either the parameters.json, or at least remove and/or rename the entities manually in HA. Impossible to know what will be coming from different Wolf models/devices.


Anyway, I'm fairly happy with how it looks now and would consider this done until anything comes up from other users.

To show off a bit:
This what it can look like:
grafik


Including an automation that disables hot water and sets the heating to "Urlaubsmodus" when nobody is home.

I'll update my setup to make sure nothing broke with the refactoring.

**Comment by zivillian** [comment]
I've found and (hopefully) fixed the quoting issue for `Uhrzeit_Ende`

**Comment by zivillian** [comment]
> Anyway, I'm fairly happy with how it looks now and would consider this done until anything comes up from other users.

I'd say let's wait until next year (one and a half week) - right now I'm also fine with this PR. The next step would be a solution for the parameter.json.

**Comment by testkandidat** [comment]
I installed the Add-on but the Add-on stops right after the starting process.

> log
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
++ echo '{' '"Devices":' '[' '{' '"ReadBusAddress":' '"0x8",' '"DeviceTemplateId":' 18000, '"Parameter":' '[' 18005, 18006, 18008, 18012, 18016, 18025, 18026, 18033, 18034, 18035, 18051, 18054, 18068, 18076, 18102, 18110, 18113, 18114, 18115, 18116, 18117, 18118, 18119, 18120, 18121, 18124, 18125, 18126, 18127, 18128, 18129, 18130, 18131, 18132, 18133, 18134, 18135, 18136, 18137, 18138, 18139, 18141, 18142, 18143, 18145, 18148, 18152, 18154, 18155, 18150, 18149, 18140, 18123, 18156, 18157, 18032, 18122 ']' '},' '{' '"ReadBusAddress":' '"0x35",' '"DeviceTemplateId":' 22000, '"Parameter":' '[' 22001, 22021, 22022, 22023, 22025, 22026, 22027, 22028, 22029, 22030, 22031, 22032, 22033, 22034, 22035, 22036, 22039, 22040, 22041, 22109, 22111, 22113, 22114, 22116, 32378, 32379, 32380, 32381, 32382, 32383, 32384, 32385, 32386, 32387, 32388, 32389, 32390, 32391, 32392, 32393, 32394, 32395, 32396, 32397, 32398, 33000, 33001, 33002, 33003, 33004, 33005, 33006, 33007, 33008, 33009, 33010, 33011, 22043, 22044, 22045, 22046, 22091, 22107, 22108, 22110, 22104 ']' '},' '{' '"ReadBusAddress":' '"0x76",' '"DeviceTemplateId":' 6000, '"Parameter":' '[' 6045, 6046, 6050, 6051, 6052, 6053, 6058, 6059, 6060, 6063, 6000, 6008, 6039, 6044, 6001, 6002, 6003, 6004, 6005, 6006, 6007, 6012, 6013, 6014, 6015, 6016, 6018, 6019, 6020, 6021, 6022, 6023, 6025, 6026, 6027, 6028, 6029, 6030, 6031, 6032, 6035, 6038 ']' '},' '{' '"ReadBusAddress":' '"0x35",' '"DeviceTemplateId":' 34000, '"Parameter":' '[' 32000, 32001, 32002, 32003, 32004, 32005, 32006, 32007, 32008, 32009, 32010, 32011, 32012, 32013, 32014, 32015, 32016, 32017, 32018, 32019, 32020, 34000, 34001, 34005, 34006, 34007, 34008, 34009, 34010, 34011, 34012, 34013, 34014, 34015, 34016, 34026, 34027, 34004 ']' '},' '{' '"ReadBusAddress":' '"0x00",' '"DeviceTemplateId":' 19000, '"Parameter":' '[' 19000, 19001, 19002, 19003, 19004, 19007, 19011, 19012, 19014, 19015, 19016, 19019, 19020, 19021 ']' '},' '{' '"ReadBusAddress":' '"0x3C",' '"DeviceTemplateId":' 23000, '"Parameter":' '[' 23010, 23011, 23012, 23013, 23014, 23015, 23017, 23018, 23019, 23020, 23021, 23022, 23023, 23024, 23025, 23026, 23027, 23028, 23030, 23031, 23032, 23033, 23034, 23035, 23036, 23037, 23038, 23039, 23040, 23041, 23042, 23043, 23044, 23045, 23046, 23047, 23048, 23050 ']' '},' '{' '"ReadBusAddress":' '"0x35",' '"DeviceTemplateId":' 35000, '"Parameter":' '[' 32021, 32022, 32023, 32024, 32025, 32026, 32027, 32028, 32029, 32030, 32031, 32032, 32033, 32034, 32035, 32036, 32037, 32038, 32039, 32040, 32041, 35001, 35004, 35009, 35010 ']' '}' ']' '}'
Starting ism7mqtt --hass-id=Wolf --interval=60 -t /parameter.json -d
++ ISM_ARGS='--hass-id=Wolf --interval=60 -t /parameter.json'
++ [[ true == \t\r\u\e ]]
++ ISM_ARGS+=' -d'
++ echo 'Starting ism7mqtt --hass-id=Wolf --interval=60 -t /parameter.json -d'
++ cd /app
++ /app/ism7mqtt --hass-id=Wolf --interval=60 -t /parameter.json -d
> <?xml version="1.0" encoding="utf-16"?><direct-logon-request xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><password>Messer2020</password></direct-logon-request>
< <?xml version="1.0" encoding="utf-8"?><direct-logon-response state="ok" sid=""><installationname>ISM7</installationname><serialnumber>5410ec0e0359</serialnumber><date-time>2022-12-22T20:37:04</date-time><ism-softwareversion>210.47.1.5.2.1</ism-softwareversion><ism-hardwareversion>1.0</ism-hardwareversion><type>ISM7i</type><wlan-connected>true</wlan-connected></direct-logon-response>
> <?xml version="1.0" encoding="utf-16"?><read-systemconfig-request xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" sid="" />
< ﻿<?xml version="1.0" encoding="utf-8"?><read-systemconfig-response sid=""><gateway type="ISM7i" softwareNumber="1" softwareVersion="210" wlan="false" g3="false"/><busconfig type="ebus"><busDevices><busDevice ba="0x8" sv="0x60" sr="0x1" cfg="0x405A" did="0x21"/><busDevice ba="0x35" sv="0x2" sr="0x4" cfg="0xC000" did="0x20"/><busDevice ba="0x3C" sv="0xFF" sr="0xFF" cfg="0x322" did="0x16"/><busDevice ba="0x76" sv="0x2" sr="0x27" cfg="0x8000" did="0x15"/></busDevices></busconfig></read-systemconfig-response>
> <?xml version="1.0" encoding="utf-16"?><tbreq xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" bn="1" gw="1" ae="false" ty="pull"><ird in="35" ba="0x35" /><ird in="41" ba="0x35" /><ird in="42" ba="0x35" /><ird in="257" ba="0x35" /><ird in="271" ba="0x35" /><ird in="388" ba="0x35" /><ird in="408" ba="0x35" /><ird in="618" ba="0x35" /><ird in="701" ba="0x35" /><ird in="702" ba="0x35" /><ird in="10121" ba="0x35" /><ird in="10127" ba="0x35" /><ird in="10130" ba="0x35" /><ird in="10141" ba="0x35" /><ird in="10145" ba="0x35" /><ird in="10146" ba="0x35" /><ird in="10147" ba="0x35" /><ird in="10148" ba="0x35" /><ird in="10149" ba="0x35" /><ird in="10150" ba="0x35" /><ird in="10151" ba="0x35" /><ird in="10152" ba="0x35" /><ird in="10153" ba="0x35" /><ird in="10154" ba="0x35" /><ird in="10160" ba="0x35" /><ird in="10161" ba="0x35" /><ird in="10162" ba="0x35" /><ird in="10163" ba="0x35" /><ird in="10165" ba="0x35" /><ird in="10178" ba="0x35" /><ird in="10180" ba="0x35" /><ird in="10181" ba="0x35" /><ird in="10185" ba="0x35" /><ird in="10812" ba="0x35" /><ird in="10920" ba="0x35" /><ird in="278" ba="0x35" /><ird in="279" ba="0x35" /><ird in="651" ba="0x35" /><ird in="10107" ba="0x35" /><ird in="10108" ba="0x35" /><ird in="10109" ba="0x35" /><ird in="10110" ba="0x35" /><ird in="10111" ba="0x35" /><ird in="10113" ba="0x35" /><ird in="10119" ba="0x35" /><ird in="10155" ba="0x35" /><ird in="10156" ba="0x35" /><ird in="10159" ba="0x35" /><ird in="10164" ba="0x35" /><ird in="10165" ba="0x35" /><ird in="10179" ba="0x35" /><ird in="19" ba="0x35" /><ird in="10134" ba="0x35" /><ird in="10158" ba="0x35" /></tbreq>
> <?xml version="1.0" encoding="utf-16"?><tbreq xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" bn="2" gw="1" ae="false" ty="pull"><ird in="2" ba="0x8" /><ird in="3" ba="0x8" /><ird in="12" ba="0x8" /><ird in="13" ba="0x8" /><ird in="14" ba="0x8" /><ird in="22" ba="0x8" /><ird in="31" ba="0x8" /><ird in="33" ba="0x8" /><ird in="34" ba="0x8" /><ird in="39" ba="0x8" /><ird in="45" ba="0x8" /><ird in="319" ba="0x8" /><ird in="320" ba="0x8" /><ird in="322" ba="0x8" /><ird in="323" ba="0x8" /><ird in="328" ba="0x8" /><ird in="339" ba="0x8" /><ird in="341" ba="0x8" /><ird in="342" ba="0x8" /><ird in="345" ba="0x8" /><ird in="346" ba="0x8" /><ird in="363" ba="0x8" /><ird in="367" ba="0x8" /><ird in="370" ba="0x8" /><ird in="371" ba="0x8" /><ird in="376" ba="0x8" /><ird in="383" ba="0x8" /><ird in="384" ba="0x8" /><ird in="410" ba="0x8" /><ird in="550" ba="0x8" /><ird in="551" ba="0x8" /><ird in="552" ba="0x8" /><ird in="553" ba="0x8" /><ird in="554" ba="0x8" /><ird in="633" ba="0x8" /><ird in="644" ba="0x8" /><ird in="1486" ba="0x8" /><ird in="2651" ba="0x8" /><ird in="2751" ba="0x8" /><ird in="10010" ba="0x8" /><ird in="10013" ba="0x8" /><ird in="10014" ba="0x8" /><ird in="10017" ba="0x8" /><ird in="10028" ba="0x8" /><ird in="10030" ba="0x8" /><ird in="10033" ba="0x8" /><ird in="10041" ba="0x8" /><ird in="10063" ba="0x8" /><ird in="10067" ba="0x8" /><ird in="10068" ba="0x8" /><ird in="10071" ba="0x8" /><ird in="10075" ba="0x8" /><ird in="10076" ba="0x8" /><ird in="10078" ba="0x8" /><ird in="10804" ba="0x8" /><ird in="10805" ba="0x8" /><ird in="65019" ba="0x8" /></tbreq>
> <?xml version="1.0" encoding="utf-16"?><tbreq xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema" bn="3" gw="1" ae="false" ty="pull"><ird in="404" ba="0x76" /><ird in="405" ba="0x76" /><ird in="410" ba="0x76" /><ird in="718" ba="0x76" /><ird in="757" ba="0x76" /><ird in="758" ba="0x76" /><ird in="759" ba="0x76" /><ird in="761" ba="0x76" /><ird in="837" ba="0x76" /><ird in="968" ba="0x76" /><ird in="969" ba="0x76" /><ird in="974" ba="0x76" /><ird in="975" ba="0x76" /><ird in="2423" ba="0x76" /><ird in="2424" ba="0x76" /><ird in="2427" ba="0x76" /><ird in="2428" ba="0x76" /><ird in="2476" ba="0x76" /><ird in="2477" ba="0x76" /><ird in="2478" ba="0x76" /><ird in="2508" ba="0x76" /><ird in="2516" ba="0x76" /><ird in="2601" ba="0x76" /><ird in="2602" ba="0x76" /><ird in="2603" ba="0x76" /><ird in="2604" ba="0x76" /><ird in="4910" ba="0x76" /><ird in="4913" ba="0x76" /><ird in="4918" ba="0x76" /><ird in="4919" ba="0x76" /><ird in="4920" ba="0x76" /><ird in="4929" ba="0x76" /><ird in="20036" ba="0x76" /><ird in="20037" ba="0x76" /><ird in="20038" ba="0x76" /><ird in="20039" ba="0x76" /><ird in="20040" ba="0x76" /><ird in="20041" ba="0x76" /><ird in="20042" ba="0x76" /><ird in="65019" ba="0x76" /></tbreq>
> <?xml version="1.0" encoding="utf-16"?><tbreq xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" bn="4" gw="1" ae="false" ty="pull"><ird in="1" ba="0x3C" /><ird in="2" ba="0x3C" /><ird in="3" ba="0x3C" /><ird in="4" ba="0x3C" /><ird in="7" ba="0x3C" /><ird in="8" ba="0x3C" /><ird in="9" ba="0x3C" /><ird in="10" ba="0x3C" /><ird in="11" ba="0x3C" /><ird in="12" ba="0x3C" /><ird in="13" ba="0x3C" /><ird in="14" ba="0x3C" /><ird in="15" ba="0x3C" /><ird in="16" ba="0x3C" /><ird in="17" ba="0x3C" /><ird in="18" ba="0x3C" /><ird in="19" ba="0x3C" /><ird in="20" ba="0x3C" /><ird in="21" ba="0x3C" /><ird in="22" ba="0x3C" /><ird in="23" ba="0x3C" /><ird in="24" ba="0x3C" /><ird in="25" ba="0x3C" /><ird in="26" ba="0x3C" /><ird in="27" ba="0x3C" /><ird in="33" ba="0x3C" /><ird in="48" ba="0x3C" /><ird in="50" ba="0x3C" /><ird in="51" ba="0x3C" /></tbreq>
MQTTnet.Exceptions.MqttProtocolViolationException: The character '+' is not allowed in topics.
   at MQTTnet.Protocol.MqttTopicValidator.ThrowIfInvalid(String topic)
   at MQTTnet.Protocol.MqttTopicValidator.ThrowIfInvalid(MqttApplicationMessage applicationMessage)
   at MQTTnet.Client.MqttClient.PublishAsync(MqttApplicationMessage applicationMessage, CancellationToken cancellationToken)
   at ism7mqtt.Program.PublishDiscoveryInfo(Ism7Config config, IMqttClient mqttClient, CancellationToken cancellationToken) in /app/Program.cs:line 186
   at ism7mqtt.Ism7Client.LoadInitialValuesAsync(CancellationToken cancellationToken) in /app/ISM7/Ism7Client.cs:line 285
   at ism7mqtt.ResponseDispatcher.DispatchAsync(IResponse response, CancellationToken cancellationToken) in /app/ISM7/ResponseDispatcher.cs:line 32
   at ism7mqtt.Ism7Client.ReadPipeAsync(PipeReader source, CancellationToken cancellationToken) in /app/ISM7/Ism7Client.cs:line 190
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by zivillian** [comment]
@testkandidat thanks for testing and your feedback. I added a commit which should replace the offending `+`, but I'm unsure what @b3nn0 needs to do to update the HA Addon. I've already trigger a new docker image.

**Comment by b3nn0** [comment]
Update for the Add-on is pushed. It should be offered if you go to the addon-store, click the dot-menu in the top right and hit "check for updates" or something.

In fact, I _think_ it should also work if you just hit the "Neu Bauen" button in the addon. I think it should just pull the latest docker image from zivilian.

**Comment by b3nn0** [comment]
@zivillian 
Actually, I think it would be better if we drop the "MQTT-Escaping function, and just make the SafeName more strict to not allow /.+
This would also resolve the issue I described earlier, that we have to subscribe to "1x_Warmwasser", but publish to "/set/1x Warmwasser".

Also requires the respective change to discovery, to tell HA that the command_topic is now constructed with the SafeName of course.

**Comment by zivillian** [comment]
@b3nn0 I totally understand your point, but I (personally) like the json keys without replaced spaces - that's why I kept it this way until now. I will think about this and also double check the publishing issue in the next days (this needs to be fixed) - if you have an idea or suggestion feel free.

**Comment by b3nn0** [comment]
Aah, makes sense, didn't think about that.. so I guess it is somewhat inconsistent either way. I can live with it and it works as it is - just found it a bit odd.
Not a big deal - whatever floats your boat.

**Comment by testkandidat** [comment]
Now it's working. Thank you. But i ran into a new problem. I have a cwl300 ventilation. All actors are shown correctly but the sensors are not. Every value is negative, either -1 or -0.1. But this is probably an issue of ism7 not the integration into ha.

**Comment by zivillian** [comment]
wow interesting - there is another [issue ](../issues/34)with exactly the same symptom

**Comment by b3nn0** [comment]
So I've been running with this for a while now and everything seems to work well.
The only thing I'm considering now is removing the `<ControlType>NO_DISPLAY</ControlType>` parameters from discovery. At least for my CGW-2, these seem to be duplicates of other parameters that have a suitable ControlType.. or do you happen to know more about these and they actually do provide something useful in some cases?

**Comment by zivillian** [comment]
I have no further info, but it sounds reasonable to hide them.

**Comment by zivillian** [comment]
I've triggered a new docker build - the new image is available at docker hub.

**Comment by infocfc** [comment]
Sorry for being apparently stupid, but can one of you post a short instruction how to add this to HomeAssistant? I'm unsuccesful finding or adding the add-on repository?!

**Comment by b3nn0** [comment]
Are you running Supervised or HassOS? Ten go to settings, Add-ons, Add-on store, then add this repository via the 3-dot-menu in the top right: https://github.com/b3nn0/hassio-addon-ism7mqtt

If there is no Add-ons menu item in the settings, you are probably only running core or container install methods of HA. Then you will have to use docker to manually install the ism7mqtt container.

**Comment by infocfc** [comment]
Yeah, thanks. I had to restart HA (running HassOS) to have the add-on show up after adding the repository. It's running fine, will add some comments later.

**Comment by zivillian** [comment]
@testkandidat I've published a new docker image, which should also support the CWL300 - can you test it?

**Comment by zivillian** [comment]
@b3nn0 I'd like to fix the consistency issue between reading and writing before merging this PR. This may involve some major code changes.

If it's OK with you, i'll try to adapt your branch to this afterwards, and it would be great if you could test again to make sure it still works.

**Comment by b3nn0** [comment]
Sure, sounds fine to me.

**Comment by testkandidat** [comment]
> @testkandidat I've published a new docker image, which should also support the CWL300 - can you test it?

I tested it and it works. Thank you

but I have  issues with updating values for almost all parameters. From time to time the values aren't updated. The timestamp which indicates the last change of value  is then the same for every parameter.
And it es not possible at all to set values.

**Comment by zivillian** [comment]
After looking at the discovery topics I'd suggest, that we add the BusAddress of the devices to the `discoveryTopic` or `uniqueId` to make sure, that colliding parameter names between different devices don't overwrite themselves.
I'm not sure if we need to add it to the device json object as well, since I don't know much about HA.

**Comment by zivillian** [comment]
As an example: I have the parameter "Rücklauftemperatur" on two of my devices.

**Comment by b3nn0** [comment]
Regarding functionality: Unfortunately, it does not seem to work any more.
Reading works fine, setting topics without spaces too, but setting topics with spaces not.
With this patch, HA will now publish to topics where spaces are replaced by _, but ism7mqtt will not understand it.

E.g. I tried to set "Pumpenleistung HK minimal".
grafik

As you can see, the value is not set. In stdout I can see this: `nothing to send for topic 'Wolf/192.168.188.83/CGB-2_0x8' with payload '44'`.
Note that publishing to the old topic "Pumpenleistung HK Minimal" doesn't seem to work either - I can't seem to be able to set parameters with a space at all any more?

Regarding IDs: The intention was to add the deviceName in the unique ID and discovery topic, assuming that was unique enough (is it?)
Looking at the topics now, though, the device name does indeed not seem to be in there - not sure if due to latest patch or if it was always like that.
Looking at my old patches I think I indeed only set that for the object_id, not for the discovery topic or the unique_id? hmm.. I was sure I did that.

Regarding terminology:
- The topic we publish the discovery info to does not really matter, as long as it is something like `homeassistant/sensor/...`. It just needs to be unique, so we don't accidentally overwrite previously published info.
- The (optional) entity_id - which we don't give - is the ID of a sensor/switch/... that can be used by the user to e.g. do automations with. It is the main identifier to address entities in HA. If it is not given, HA will automatically derive it from the `object_id` or the `name`.
- The (optional) object_id is just a helper for HA to generate a unique entity_id (the device name is still in there.. so at least HA generates unique entity_ids) 
- The (optional) unique_id is an arbitrary unique identifier for the respective sensor/switch/.... The user rarely sees it, but HA will internally use it. If it is set, HA allows the user to change properties of the entity via the UI. E.g. to set a different icon or a different name. HA will then internally keep a mapping `uniqueId->icon override` etc.

So yes, the uniqueId and discovery topic _must_ be unique, the object_id _should_ be unique (otherwise HA will just append a "2", "3", ... to the generated entity_id, which works but is not nice).

Should I change that or do you want to do it? If I do it, do you think the device name is enough? Or is the bus address required to distinguish?

**Comment by b3nn0** [comment]
Oh, just noticed one more issue:
The discovery topic may only contain characters [a-zA-Z0-9_-]. So this creates a warning in HA now:
`Received message on illegal discovery topic 'homeassistant/number/Wolf_Max._Speicherladezeit/config'. The topic contains not allowed characters`

**Comment by zivillian** [comment]
I fixed the writing issue and published a new docker image.

For the discovery topic I would suggest to use the  BusAddress and Parameter ID: `Wolf_0x8_18125` This is unique, fits into the charset and allows the user to map the properties back to the IDs in the json file.

**Comment by b3nn0** [comment]
Ok, makes sense I suppose. Probably for all of them (object I'd, discovery topic, unique I'd).
Do you want or should I?

**Comment by zivillian** [comment]
go for it ;-)

**Comment by b3nn0** [comment]
Alright, so I checked how other integrations generate their IDs, and they all put quite a bit of info in there, so I now made it like this: `{discoveryId}_{device.Name}_{device.WriteAddress}_{parameter.PTID}_{parameter.Name}`
plus some laundering to make sure it's a valid HA id.
Additionally, I had to do some changes to fix writing.. not sure if this is correct though? It seems to work well now.

**Comment by zivillian** [comment]
Oh sorry, I forgot to merge the write fix to this branch, but I'll take care of this.

**Comment by b3nn0** [comment]
Are you sure == instead of startswith is correct? For me, this compared the full topic name (incl Parameter Name) with just the device-part of the topic, yielding no result...? Am I missing something?

**Comment by zivillian** [comment]
I'll test locally, but everything after `/set/` should be in `propertyParts` - so MqttTopic should only contain `Wolf/{ip}/{name}_{ba}`

**Comment by zivillian** [comment]
For me it looks correct
grafik

**Comment by b3nn0** [comment]
Hm, indeed, seems to work fine. No idea why I had an issue with that yesterday then.
Anyway, I see you already pushed to docker hub, I'll push an update for the HA Addon then.

**Comment by zivillian** [comment]
I've pushed another commit (and docker image), but this is only for a rare edge case. From my side, this looks good and is finished.

**Comment by b3nn0** [comment]
I agree, looks quite nice in HA now.

**Comment by zivillian** [comment]
Thank you very much!

**Pull request merged**
